Commit after cloning the repo
microhass/portfolio_review pull request #1
Opened 2023-05-01 11:58 UTC by hassanShakur

Initial commit after coning the portfolio repo.

2023-05-01 12:07 UTC, hassanShakur commented on style.css
> +  gap: 1rem;
Great job! Just remember it's always nice to use relative values that are responsive as opposed to absolute ones.

2023-05-01 12:07 UTC, hassanShakur commented on index.html
Good job!

2023-05-01 12:20 UTC, LionRouge1 requested changes
Hi @hassanShakur, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights
- Good job using Github inline comments feature :+1: 
- You phrase your comments politely :100: 

## Required Changes ♻️
- [ ] Nice work using GitHub inline comments feature:clap: However it would be nice to add a comment stating the status of the project ( if you approve it or not). Watch this [short video](https://www.loom.com/share/e847c46aa4814534b23b3a8e4dd60d6d) for more information.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-02 08:29 UTC, hassanShakur reviewed
# Approved 👌 
Your project is complete! There is nothing else to say other than... it's time to merge.
Congratulations 👏 .

2023-05-02 08:40 UTC, skyv26 requested changes
Hi @hassanShakur, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://media.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif)

 ## Required Changes ♻️
- [ ] Please adhere to the project requirements, according to the project requirement you had to make at least two inline comments but you made only one `inline-comment`. Kindly take a look at the below-attached image.

![Screenshot from 2023-05-01 16-49-19](https://user-images.githubusercontent.com/66476329/235448922-e7e38554-71b3-4513-b258-63f1d333245d.png)

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-02 08:50 UTC, hassanShakur reviewed
# PR Approved 🥂 
Your project is complete! There is nothing else to say other than... it's time to merge.
Just keep in mind what is included in the comments and make the corrections if you please.

2023-05-02 08:50 UTC, hassanShakur commented on style.css
> +}
Nice work on the background image positioning. Love it.

2023-05-02 08:50 UTC, hassanShakur commented on style.css
> +  padding: 10rem 0;
Awesome work on this. Just as a suggestion, remember to use relative dimensions when working with CSS to ensure your website remains responsive.

2023-05-02 08:58 UTC, aamirkhan2478 approved these changes
Hi @hassanShakur , 

![GIF](https://www.funimada.com/assets/images/cards/big/congrats-7.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ Good use of inline comments :+1: 
✅ Well done you did all changes given by the previous reviewer :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-02 09:00 UTC, merged